# Generated by Django 4.0.4 on 2022-04-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Lorem ipsum dolor sit amet <b>default text</b>', max_length=300),
        ),
    ]
